SymbolTable 
  [
  Symbol(
    {
      type qualifier:         Empty()
      datatype:               BuiltIn()
      name:                   Name('char')
      value or address:       Empty()
      position:               Empty()
      size:                   Empty()
    }, 
  Symbol(
    {
      type qualifier:         Empty()
      datatype:               BuiltIn()
      name:                   Name('int')
      value or address:       Empty()
      position:               Empty()
      size:                   Empty()
    }, 
  Symbol(
    {
      type qualifier:         Const()
      datatype:               FunDecl(VoidType('void'), Name('stack_fun'), [])
      name:                   Name('stack_fun')
      value or address:       Empty()
      position:               Pos(Num('1'), Num('5'))
      size:                   Empty()
    }, 
  Symbol(
    {
      type qualifier:         Const()
      datatype:               FunDecl(VoidType('void'), Name('main'), [])
      name:                   Name('main')
      value or address:       Empty()
      position:               Pos(Num('3'), Num('5'))
      size:                   Empty()
    }
  ]