SymbolTable 
  [
  Symbol(
    {
      type qualifier:         Empty()
      datatype:               FunDecl(VoidType('void'), Name('main'), [])
      name:                   Name('main')
      value or address:       Empty()
      position:               Pos(Num('1'), Num('5'))
      size:                   Empty()
    }, 
  Symbol(
    {
      type qualifier:         Writeable()
      datatype:               IntType('int')
      name:                   Name('var@main')
      value or address:       Num('0')
      position:               Pos(Num('2'), Num('6'))
      size:                   Num('1')
    }, 
  Symbol(
    {
      type qualifier:         Writeable()
      datatype:               PntrDecl(Num('1'), IntType('int'))
      name:                   Name('pntr@main')
      value or address:       Num('1')
      position:               Pos(Num('3'), Num('7'))
      size:                   Num('1')
    }
  ]