SymbolTable 
  [
  Symbol(
    {
      type qualifier:         Empty()
      datatype:               FunDecl(VoidType('void'), Name('stack_fun'), [])
      name:                   Name('stack_fun')
      value or address:       Empty()
      position:               Pos(Num('1'), Num('5'))
      size:                   Empty()
    }, 
  Symbol(
    {
      type qualifier:         Empty()
      datatype:               FunDecl(VoidType('void'), Name('main'), [])
      name:                   Name('main')
      value or address:       Empty()
      position:               Pos(Num('5'), Num('5'))
      size:                   Empty()
    }, 
  Symbol(
    {
      type qualifier:         Writeable()
      datatype:               IntType('int')
      name:                   Name('var@main')
      value or address:       Num('0')
      position:               Pos(Num('6'), Num('6'))
      size:                   Num('1')
    }
  ]