SymbolTable 
  [
  Symbol(
    {
      type qualifier:         Empty()
      datatype:               FunDecl(VoidType('void'), Name('fun1'), [])
      name:                   Name('fun1')
      value or address:       Empty()
      position:               Pos(Num('1'), Num('5'))
      size:                   Empty()
    }, 
  Symbol(
    {
      type qualifier:         Empty()
      datatype:               FunDecl(IntType('int'), Name('fun2'), [])
      name:                   Name('fun2')
      value or address:       Empty()
      position:               Pos(Num('4'), Num('4'))
      size:                   Empty()
    }, 
  Symbol(
    {
      type qualifier:         Empty()
      datatype:               FunDecl(VoidType('void'), Name('main'), [])
      name:                   Name('main')
      value or address:       Empty()
      position:               Pos(Num('8'), Num('5'))
      size:                   Empty()
    }
  ]